### ISSUE TITLE
Poker improvements

### ISSUE THREAD

**Issue by kevin1055** [blerud/lendbot#18]
* endgame and leave commands
* Show tallies in end of non-tournament games, incl. total times bought-in, etc.
* Hide "x won $" message when all but one folds
* Show "x won $, y won $" message after showdown

**Comment by blerud** [comment]
Spreadsheet integration

**Comment by kevin1055** [comment]
add reactions that can be clicked on to fold, call, etc.

**Comment by kevin1055** [comment]
Add meme hands

**Comment by kevin1055** [comment]
won't fix
