### ISSUE TITLE
Include % and absolute change with the table 

### ISSUE THREAD

**Issue by lovetoburnswhen** [blerud/lendbot#50]
Stuff like day change/ytd/wtd/mtd in the corner of the graph. Could also add options to toggle %/absolute and time frames

**Comment by kevin1055** [comment]
what about the stuff yahoo finance puts next to their charts:
![image](https://user-images.githubusercontent.com/5475211/77496955-6535b100-6e09-11ea-8875-50d559224f84.png)

**Comment by Frank5000** [comment]
> what about the stuff yahoo finance puts next to their charts:
> ![image](https://user-images.githubusercontent.com/5475211/77496955-6535b100-6e09-11ea-8875-50d559224f84.png)

Nah seems excessive
